In [ ]:
import pandas as pd
marks = pd.read_csv('https://query.data.world/s/HqjNNadqEnwSq1qnoV_JqyRJkc7o6O')


In [ ]:
print(marks.isna().sum(axis = 0))

In [ ]:
marks = marks[marks.isna().sum(axis=1)<=5]

In [ ]:
print(marks.isna().sum(axis=0))

In [ ]:
import pandas as pd
customer = pd.read_csv('https://query.data.world/s/y9rxL9mGdP6AXPiDaIL4yYm6DsfTV2')

customer['Cust_id']  customer['Cust_id'].
print(customer.head(10))

In [ ]:
import pandas as pd
customer = pd.read_csv('https://query.data.world/s/y9rxL9mGdP6AXPiDaIL4yYm6DsfTV2')
customer['Cust_id']=customer.Cust_id.str.split('_').apply(lambda x: x[1])
print(customer)

In [ ]:
import pandas as pd
rating = pd.read_csv('https://query.data.world/s/EX0EpmqwfA2UYGz1Xtd_zi4R0dQpog')

rating_update = rating.drop_duplicates()
print(rating.shape)
print(rating_update.shape)

In [ ]:
input_list = [['c1','c2','c3'],[1,2,3],[4,5,6],[7,8,9]]

d1 = input_list[1]
#type(d1)
#d1
d2= input_list[2]
d3=input_list[3]

cols = input_list[0]
data=[d1,d2,d3]

#data
df = pd.DataFrame(data,columns=cols)
df
df.describe()

In [ ]:
# Given two column names, you have to interchange the indices (positions) of the columns in a dataframe.

import pandas as pd 
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/BgyRrKq0xex8B0N3GJxbXv5WZ/test.csv")

df.columns

names = list(df.Name.values)
names

sex_val = list(df.Sex.values)
sex_val

columns = list(df.columns.values)


columns.pop(2)
columns.pop(2)

columns

df.insert(2, "Name", names, True)

df.insert(2,"Sex", sex_val,True)
df.columns
df.T.drop_duplicates().T

In [ ]:
import pandas as pd 
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/BgyRrKq0xex8B0N3GJxbXv5WZ/test.csv")

col1='Sex'
col2='Name'

names = list(df[col2].values)
sex = list(df[col1].values)

columns = list(df.columns.values)
columns.pop(2)
columns.pop(2)
columns


df.insert(2, col2, names, True)

df.insert(2,col1, sex,True)


print(df.T.drop_duplicates().T)

In [ ]:
s = 'cyqfjhcclkbxpbojgkar'
from itertools import count

def long_alphabet(input_string):
    maxsubstr = input_string[0:0] # empty slice (to accept subclasses of str)
    for start in range(len(input_string)): # O(n)
        for end in count(start + len(maxsubstr) + 1): # O(m)
            substr = input_string[start:end] # O(m)
        if len(substr) != (end - start): # found duplicates or EOS
            break
        if sorted(substr) == list(substr):
            maxsubstr=substr
    return maxsubstr

bla = (long_alphabet(s))
print("Longest substring in alphabetical order is: %s" %bl)

In [ ]:
s = 'cyqfjhcclkbxpbojgkar'
longest = ""
max =""

for i in range(len(s) -1):
    if(s[i] <= s[i+1] ):
       longest = longest + s[i]
       if(i==len(s) -2):
           longest = longest + s[i+1]
    else:
        longest  = longest + s[i]        
        if(len(longest) > len(max)):
            max = longest
        longest = ""        

if(len(s) == 1):
    longest = s


if(len(longest) > len(max)):
    print("Longest substring in alphabetical order is: " + longest)
else:
    print("Longest substring in alphabetical order is: " + max)

In [ ]:
import pandas as pd 
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/BgyRrKq0xex8B0N3GJxbXv5WZ/test.csv")
col1='Sex'
col2='Name'
col_list=list(df.columns)
col_list[df.columns.get_loc(col1)],col_list[df.columns.get_loc(col2)]=col_list[df.columns.get_loc(col2)],col_list[df.columns.get_loc(col1)]
print(df[col_list].head(3))

In [ ]:
import pandas as pd 
pd.set_option('display.max_columns', 500)
import sys,ast
df=pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/wkyk2AWYdJbqgXoRo3Y8w42nX/test.csv')

#print(df.columns)
#input_str = [['Pclass','Age'],[3,13]]
input_list = [['Pclass','Age'],[3,13]]
cols=input_list[0]#the columns to group the dataframe by

values=input_list[1]# The group to print
Pclass=values[0]
Age=values[1]
df_1 = df.groupby(cols)
#df_2=df.query("Pclass == 3 & Age == 13")
#df_2
#for index,row in df.iterrows():
#    if((row['Pclass']==3) & (row['Age']==13)):
 #      print(row)
        
        
func = [row for index,row in df.iterrows() if((row['Pclass']==3) & (row['Age']==13))]


func

data = pd.DataFrame(func)

data

type(cols)


In [ ]:
import pandas as pd
inp = [{'c1':10, 'c2':100}, {'c1':11,'c2':110}, {'c1':12,'c2':120}]
df = pd.DataFrame(inp)
#print(df)

for index, row in df.iterrows():
    if((row['c1']==10) & (row['c2']==100) ):
        print(row['c1'],row['c2'])
       
        

In [ ]:
import pandas as pd 
pd.set_option('display.max_columns', 500)
import sys,ast
df=pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/wkyk2AWYdJbqgXoRo3Y8w42nX/test.csv')

def create_sub_id(data):
    for index, row in df.iterrows():
        if((row['Pclass']==3) & (row['Age']==13)):
            data = pd.DataFrame(row)
    

In [ ]:
import pandas as pd 
pd.set_option('display.max_columns', 500)
import sys,ast
df=pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/wkyk2AWYdJbqgXoRo3Y8w42nX/test.csv')

#print(df.columns)
#input_str = [['Pclass','Age'],[3,13]]
input_list = [['Pclass','Age'],[3,13]]
cols=input_list[0]#the columns to group the dataframe by

values=input_list[1]# The group to print

df_1 = df.groupby(cols).get_group((values[0],values[1]))
df_1

In [ ]:
import pandas as pd 
pd.set_option('display.max_columns', 500)
df_2g=pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/E4QbGd18ORJpbZZkndZ5bdKBn/googleplaystore_user_reviews.csv')
df_2g.columns
df_2g.head()
df_2g.dtypes

In [ ]:
df_2g.columns

In [ ]:
df_2g_m = df_2g.groupby(['App','Translated_Review','Sentiment']).mean()
print(df_2g_m.head(5))

In [ ]:
import pandas as pd 
pd.set_option('display.max_columns', 500)

df=pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/E4QbGd18ORJpbZZkndZ5bdKBn/googleplaystore_user_reviews.csv')
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
cols = list(df.select_dtypes(exclude=numerics).columns)
print(df.groupby(cols).agg('mean').head())

In [ ]:
import pandas as pd
df = pd.read_csv('D:/upgrad/statsandEDA/popularity_1.csv')
df.describe()

In [ ]:
df.columns

In [ ]:
df[' shares'].mean()

In [ ]:
import statistics
statistics.median(df[' shares'])

In [ ]:
df[' shares'].max()

In [ ]:
def median(a, l, r): 
    n = r - l + 1
    n = (n + 1) // 2 - 1
    return n + l 


def IQR(a, n): 
    a.sort() 
  
    # Index of median of entire data 
    mid_index = median(a, 0, n) 
    print("Q2", mid_index)
  
    # Median of first half 
    Q1 = a[median(a, 0, mid_index)] 
    print("Q1",Q1)
    # Median of second half 
    Q3 = a[median(a, mid_index + 1, n)] 
    print("Q3",Q3)
    # IQR calculation 
    return (Q3 - Q1)

list_shares = list(df[' shares'])
leng = len(list_shares)
iqr = IQR(list_shares,leng)
print(iqr)

In [ ]:
list_shares
import numpy as np

elements = np.array(list_shares)
mean = np.mean(elements, axis=0)
sd = np.std(elements, axis=0)
final_list = [x for x in list_shares if (x > mean - 2 * sd)]
final_list = [x for x in final_list if (x < mean + 2 * sd)]

df = pd.DataFrame(final_list)
df.describe()

In [ ]:
import pandas as pd
df_out = pd.read_csv('D:/upgrad/statsandEDA/popularity_1.csv')
filt_df = df_out[' shares']


In [ ]:
low = .05
high = .95
quant_df = filt_df.quantile([low, high])
print(quant_df)


In [ ]:
filt_df = filt_df.apply(lambda x: x[(x>quant_df.loc[low]) & (x < quant_df.loc[high])])

In [ ]:
import pandas as pd
df_out_1 = pd.read_csv('D:/upgrad/statsandEDA/EDA_census_updated_1.2.csv')


In [ ]:
df_out_1

In [ ]:
df_out_1['literacy_rate']=(df_out_1['Total_Persons_lit']/df_out_1['Total_Persons'])*100

In [ ]:
df_out_1

In [ ]:
input_list = [[1,2,3,4,5,6,7],[1,3,7]]
series1=pd.Series(input_list[0])
series2=pd.Series(input_list[1])

list_new= []
for i in series1:
    for j in series2:
        if(i==j):
            list_new.append(series2.get_loc(j))
print(list_new)
            

In [ ]:
input_list = [[1,2,3,4,5,6,7],[1,3,7]]
series1=pd.Series(input_list[0])
series2=pd.Series(input_list[1])

input_list_1=pd.Series(list(set(series1).intersection(set(series2))))
input_list_1

In [ ]:
input_list = [[1,2,3,4,5,6,7],[1,3,7]]
series1=pd.Series(input_list[0])
series2=pd.Series(input_list[1])


check_1=[pd.Index(series1).get_loc(num) for num in series2]
check_1

In [ ]:
input_list = [[1,2,3,4,5,6,7],[1,3,7]]
series1=pd.Series(input_list[0])
series2=pd.Series(input_list[1])

check_2=[]
for num in series2:
    check_2.append(pd.Index(series1).get_loc(num))
    
check_2
 

In [8]:
import pandas as pd 
url='https://media-doselect.s3.amazonaws.com/generic/o8oEby20V1LLAZzpABwWa7R1n/heart.csv'
df=pd.read_csv(url)
pd.set_option('display.max_columns', 500)
print(df.reindex(index=df.index[::-1]).head(4))

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
302   57    0   1       130   236    0        0      174      0      0.0   
301   57    1   0       130   131    0        1      115      1      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
299   45    1   3       110   264    0        1      132      0      1.2   

     slope  ca  thal  target  
302      1   1     2       0  
301      1   1     3       0  
300      1   2     3       0  
299      1   0     3       0  


In [79]:
import pandas as pd
url='https://media-doselect.s3.amazonaws.com/generic/1YZQ77KLVyegqroyJgk5Z7d1/titaniMod2.csv'
df=pd.read_csv(url)
df.head(10)

Age Cabin        Date Embarked     Fare  \
0  34.5   NaN  1979-10-07        Q   7.8292   
1  47.0   NaN  1979-10-07        S   7.0000   
2  62.0   NaN  1979-10-07        Q   9.6875   
3  27.0   NaN  1979-10-07        S   8.6625   
4  22.0   NaN  1979-10-07        S  12.2875   
5  14.0   NaN  1979-10-07        S   9.2250   
6  30.0   NaN  1979-10-07        Q   7.6292   
7  26.0   NaN  1979-10-07        S  29.0000   
8  18.0   NaN  1979-10-07        C   7.2292   
9  21.0   NaN  1979-10-07        S  24.1500   

                                           Name  Parch  PassengerId  Pclass  \
0                              Kelly, Mr. James    0.0        892.0     3.0   
1              Wilkes, Mrs. James (Ellen Needs)    0.0        893.0     3.0   
2                     Myles, Mr. Thomas Francis    0.0        894.0     2.0   
3                              Wirz, Mr. Albert    0.0        895.0     3.0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1.0        896.0     3.0   
5                    Svensson, Mr. Johan Cervin    0.0        897.0     3.0   
6                          Connolly, Miss. Kate    0.0        898.0     3.0   
7                  Caldwell, Mr. Albert Francis    1.0        899.0     2.0   
8     Abrahim, Mrs. Joseph (Sophie Halaut Easu)    0.0        900.0     3.0   
9                       Davies, Mr. John Samuel    0.0        901.0     3.0   

      Sex ShipName  SibSp     Ticket  
0    male  Titanic    0.0     330911  
1  female  Titanic    1.0     363272  
2    male  Titanic    0.0     240276  
3    male  Titanic    0.0     315154  
4  female  Titanic    1.0    3101298  
5    male  Titanic    0.0       7538  
6  female  Titanic    0.0     330972  
7    male  Titanic    1.0     248738  
8  female  Titanic    0.0       2657  
9    male  Titanic    2.0  A/4 48871

In [80]:
df.shape

(836, 13)

In [81]:
df.isnull().all(axis=1).sum()

418

In [82]:
df.isnull().any(axis=1)

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12     False
13      True
14     False
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24     False
25      True
26     False
27      True
28     False
29      True
       ...  
806     True
807     True
808     True
809     True
810     True
811     True
812     True
813     True
814     True
815     True
816     True
817     True
818     True
819     True
820     True
821     True
822     True
823     True
824     True
825     True
826     True
827     True
828     True
829     True
830     True
831     True
832     True
833     True
834     True
835     True
Length: 836, dtype: bool

In [83]:
df.isnull().all(axis=1)

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
806     True
807     True
808     True
809     True
810     True
811     True
812     True
813     True
814     True
815     True
816     True
817     True
818     True
819     True
820     True
821     True
822     True
823     True
824     True
825     True
826     True
827     True
828     True
829     True
830     True
831     True
832     True
833     True
834     True
835     True
Length: 836, dtype: bool

In [84]:
df.isnull().all(axis=1).sum()

418

In [85]:
df.isnull().sum(axis=1)

0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       1
9       1
10      2
11      1
12      0
13      1
14      0
15      1
16      1
17      1
18      1
19      1
20      1
21      1
22      2
23      1
24      0
25      1
26      0
27      1
28      0
29      2
       ..
806    13
807    13
808    13
809    13
810    13
811    13
812    13
813    13
814    13
815    13
816    13
817    13
818    13
819    13
820    13
821    13
822    13
823    13
824    13
825    13
826    13
827    13
828    13
829    13
830    13
831    13
832    13
833    13
834    13
835    13
Length: 836, dtype: int64

In [37]:
round(100*(df.isnull().sum()/len(df.index)), 2)

Age            60.29
Cabin          89.11
Date           50.00
Embarked       50.00
Fare           50.12
Name           50.00
Parch          50.00
PassengerId    50.00
Pclass         50.00
Sex            50.00
ShipName       50.00
SibSp          50.00
Ticket         50.00
dtype: float64

In [86]:
df.columns

Index(['Age', 'Cabin', 'Date', 'Embarked', 'Fare', 'Name', 'Parch',
       'PassengerId', 'Pclass', 'Sex', 'ShipName', 'SibSp', 'Ticket'],
      dtype='object')

In [87]:
df[df.isnull().sum(axis=1) == 13]

Age Cabin Date Embarked  Fare Name  Parch  PassengerId  Pclass  Sex  \
418  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
419  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
420  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
421  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
422  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
423  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
424  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
425  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
426  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
427  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
428  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
429  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
430  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
431  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
432  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
433  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
434  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
435  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
436  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
437  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
438  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
439  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
440  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
441  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
442  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
443  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
444  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
445  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
446  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
447  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
..   ...   ...  ...      ...   ...  ...    ...          ...     ...  ...   
806  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
807  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
808  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
809  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
810  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
811  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
812  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
813  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
814  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
815  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
816  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
817  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
818  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
819  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
820  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
821  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
822  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
823  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
824  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
825  NaN   NaN  NaN      NaN   NaN  NaN    NaN          NaN     NaN  NaN   
826  NaN   NaN  NaN      NaN   NaN  NaN    NaN       

In [88]:
100*(len(df[df.isnull().sum(axis=1) <= 5].index) / len(df.index))

50.0

In [89]:
df = df[df.isnull().sum(axis=1) <= 5]

In [90]:
df.shape

(418, 13)

In [91]:
round(100*(df.isnull().sum()/len(df.index)), 2)

Age            20.57
Cabin          78.23
Date            0.00
Embarked        0.00
Fare            0.24
Name            0.00
Parch           0.00
PassengerId     0.00
Pclass          0.00
Sex             0.00
ShipName        0.00
SibSp           0.00
Ticket          0.00
dtype: float64

In [67]:
import numpy as np
df = df[~np.isnan(df['Age'])]
df

Age            Cabin        Date Embarked      Fare  \
0    34.5              NaN  1979-10-07        Q    7.8292   
1    47.0              NaN  1979-10-07        S    7.0000   
2    62.0              NaN  1979-10-07        Q    9.6875   
3    27.0              NaN  1979-10-07        S    8.6625   
4    22.0              NaN  1979-10-07        S   12.2875   
5    14.0              NaN  1979-10-07        S    9.2250   
6    30.0              NaN  1979-10-07        Q    7.6292   
7    26.0              NaN  1979-10-07        S   29.0000   
8    18.0              NaN  1979-10-07        C    7.2292   
9    21.0              NaN  1979-10-07        S   24.1500   
11   46.0              NaN  1979-10-07        S   26.0000   
12   23.0              B45  1979-10-07        S   82.2667   
13   63.0              NaN  1979-10-07        S   26.0000   
14   47.0              E31  1979-10-07        S   61.1750   
15   24.0              NaN  1979-10-07        C   27.7208   
16   35.0              NaN  1979-10-07        Q   12.3500   
17   21.0              NaN  1979-10-07        C    7.2250   
18   27.0              NaN  1979-10-07        S    7.9250   
19   45.0              NaN  1979-10-07        C    7.2250   
20   55.0              NaN  1979-10-07        C   59.4000   
21    9.0              NaN  1979-10-07        S    3.1708   
23   21.0              NaN  1979-10-07        C   61.3792   
24   48.0  B57 B59 B63 B66  1979-10-07        C  262.3750   
25   50.0              NaN  1979-10-07        S   14.5000   
26   22.0              B36  1979-10-07        C   61.9792   
27   22.5              NaN  1979-10-07        C    7.2250   
28   41.0              A21  1979-10-07        S   30.5000   
30   50.0              NaN  1979-10-07        S   26.0000   
31   24.0              NaN  1979-10-07        S   31.5000   
32   33.0              NaN  1979-10-07        S   20.5750   
..    ...              ...         ...      ...       ...   
381  26.0              NaN  1979-10-07        Q    7.8792   
383  19.0              NaN  1979-10-07        S   16.1000   
385  24.0              NaN  1979-10-07        S   65.0000   
386  24.0              NaN  1979-10-07        S    7.7750   
387  57.0              NaN  1979-10-07        S   13.0000   
388  21.0              NaN  1979-10-07        Q    7.7500   
389   6.0              NaN  1979-10-07        S   21.0750   
390  23.0              B24  1979-10-07        S   93.5000   
391  51.0              D28  1979-10-07        S   39.4000   
392  13.0              NaN  1979-10-07        S   20.2500   
393  47.0              NaN  1979-10-07        S   10.5000   
394  29.0              NaN  1979-10-07        S   22.0250   
395  18.0              C31  1979-10-07        S   60.0000   
396  24.0              NaN  1979-10-07        Q    7.2500   
397  48.0              B41  1979-10-07        C   79.2000   
398  22.0              NaN  1979-10-07        S    7.7750   
399  31.0              NaN  1979-10-07        Q    7.7333   
400  30.0               C7  1979-10-07        S  164.8667   
401  38.0              NaN  1979-10-07        S   21.0000   
402  22.0              NaN  1979-10-07        C   59.4000   
403  17.0              NaN  1979-10-07        S   47.1000   
404  43.0              D40  1979-10-07        C   27.7208   
405  20.0              D38  1979-10-07        C   13.8625   
406  23.0              NaN  1979-10-07        S   10.5000   
407  50.0              C80  1979-10-07        C  211.5000   
409   3.0              NaN  1979-10-07        S   13.7750   
411  37.0              C78  1979-10-07        Q   90.0000   
412  28.0              NaN  1979-10-07        S    7.7750   
414  39.0             C105  1979-10-07        C  108.9000   
415  38.5              NaN  1979-10-07        S    7.2500   

                                                  Name  Parch  PassengerId  \
0                                     Kelly, Mr. James    0.0        892.0   
1                     Wilkes, Mrs. James (Ellen Needs)    0.0      

In [94]:
round(100*(df.isnull().sum()/len(df.index)), 2)

Age            20.57
Cabin          78.23
Date            0.00
Embarked        0.00
Fare            0.24
Name            0.00
Parch           0.00
PassengerId     0.00
Pclass          0.00
Sex             0.00
ShipName        0.00
SibSp           0.00
Ticket          0.00
dtype: float64

In [95]:
round(100*(df.isnull().sum()/len(df.index)), 2)

Age            20.57
Cabin          78.23
Date            0.00
Embarked        0.00
Fare            0.24
Name            0.00
Parch           0.00
PassengerId     0.00
Pclass          0.00
Sex             0.00
ShipName        0.00
SibSp           0.00
Ticket          0.00
dtype: float64

In [98]:
df_reserve = df

In [99]:
type(df.Date)

pandas.core.series.Series

In [101]:
df['Date'] = df['Date'].str.replace('-', ' ')
df

Age            Cabin        Date Embarked      Fare  \
0    34.5              NaN  1979 10 07        Q    7.8292   
1    47.0              NaN  1979 10 07        S    7.0000   
2    62.0              NaN  1979 10 07        Q    9.6875   
3    27.0              NaN  1979 10 07        S    8.6625   
4    22.0              NaN  1979 10 07        S   12.2875   
5    14.0              NaN  1979 10 07        S    9.2250   
6    30.0              NaN  1979 10 07        Q    7.6292   
7    26.0              NaN  1979 10 07        S   29.0000   
8    18.0              NaN  1979 10 07        C    7.2292   
9    21.0              NaN  1979 10 07        S   24.1500   
10    NaN              NaN  1979 10 07        S    7.8958   
11   46.0              NaN  1979 10 07        S   26.0000   
12   23.0              B45  1979 10 07        S   82.2667   
13   63.0              NaN  1979 10 07        S   26.0000   
14   47.0              E31  1979 10 07        S   61.1750   
15   24.0              NaN  1979 10 07        C   27.7208   
16   35.0              NaN  1979 10 07        Q   12.3500   
17   21.0              NaN  1979 10 07        C    7.2250   
18   27.0              NaN  1979 10 07        S    7.9250   
19   45.0              NaN  1979 10 07        C    7.2250   
20   55.0              NaN  1979 10 07        C   59.4000   
21    9.0              NaN  1979 10 07        S    3.1708   
22    NaN              NaN  1979 10 07        S   31.6833   
23   21.0              NaN  1979 10 07        C   61.3792   
24   48.0  B57 B59 B63 B66  1979 10 07        C  262.3750   
25   50.0              NaN  1979 10 07        S   14.5000   
26   22.0              B36  1979 10 07        C   61.9792   
27   22.5              NaN  1979 10 07        C    7.2250   
28   41.0              A21  1979 10 07        S   30.5000   
29    NaN              NaN  1979 10 07        C   21.6792   
..    ...              ...         ...      ...       ...   
388  21.0              NaN  1979 10 07        Q    7.7500   
389   6.0              NaN  1979 10 07        S   21.0750   
390  23.0              B24  1979 10 07        S   93.5000   
391  51.0              D28  1979 10 07        S   39.4000   
392  13.0              NaN  1979 10 07        S   20.2500   
393  47.0              NaN  1979 10 07        S   10.5000   
394  29.0              NaN  1979 10 07        S   22.0250   
395  18.0              C31  1979 10 07        S   60.0000   
396  24.0              NaN  1979 10 07        Q    7.2500   
397  48.0              B41  1979 10 07        C   79.2000   
398  22.0              NaN  1979 10 07        S    7.7750   
399  31.0              NaN  1979 10 07        Q    7.7333   
400  30.0               C7  1979 10 07        S  164.8667   
401  38.0              NaN  1979 10 07        S   21.0000   
402  22.0              NaN  1979 10 07        C   59.4000   
403  17.0              NaN  1979 10 07        S   47.1000   
404  43.0              D40  1979 10 07        C   27.7208   
405  20.0              D38  1979 10 07        C   13.8625   
406  23.0              NaN  1979 10 07        S   10.5000   
407  50.0              C80  1979 10 07        C  211.5000   
408   NaN              NaN  1979 10 07        Q    7.7208   
409   3.0              NaN  1979 10 07        S   13.7750   
410   NaN              NaN  1979 10 07        Q    7.7500   
411  37.0              C78  1979 10 07        Q   90.0000   
412  28.0              NaN  1979 10 07        S    7.7750   
413   NaN              NaN  1979 10 07        S    8.0500   
414  39.0             C105  1979 10 07        C  108.9000   
415  38.5              NaN  1979 10 07        S    7.2500   
416   NaN              NaN  1979 10 07        S    8.0500   
417   NaN              NaN  1979 10 07        C   22.3583   

                                                  Name  Parch  PassengerId  \
0                                     Kelly, Mr. James    0.0        892.0   
1                     Wilkes, Mrs. James (Ellen Needs)    0.0      

In [102]:
df.columns

Index(['Age', 'Cabin', 'Date', 'Embarked', 'Fare', 'Name', 'Parch',
       'PassengerId', 'Pclass', 'Sex', 'ShipName', 'SibSp', 'Ticket'],
      dtype='object')

In [105]:
df

Age            Cabin        Date Embarked      Fare  \
0    34.5              NaN  1979 10 07        Q    7.8292   
1    47.0              NaN  1979 10 07        S    7.0000   
2    62.0              NaN  1979 10 07        Q    9.6875   
3    27.0              NaN  1979 10 07        S    8.6625   
4    22.0              NaN  1979 10 07        S   12.2875   
5    14.0              NaN  1979 10 07        S    9.2250   
6    30.0              NaN  1979 10 07        Q    7.6292   
7    26.0              NaN  1979 10 07        S   29.0000   
8    18.0              NaN  1979 10 07        C    7.2292   
9    21.0              NaN  1979 10 07        S   24.1500   
10    NaN              NaN  1979 10 07        S    7.8958   
11   46.0              NaN  1979 10 07        S   26.0000   
12   23.0              B45  1979 10 07        S   82.2667   
13   63.0              NaN  1979 10 07        S   26.0000   
14   47.0              E31  1979 10 07        S   61.1750   
15   24.0              NaN  1979 10 07        C   27.7208   
16   35.0              NaN  1979 10 07        Q   12.3500   
17   21.0              NaN  1979 10 07        C    7.2250   
18   27.0              NaN  1979 10 07        S    7.9250   
19   45.0              NaN  1979 10 07        C    7.2250   
20   55.0              NaN  1979 10 07        C   59.4000   
21    9.0              NaN  1979 10 07        S    3.1708   
22    NaN              NaN  1979 10 07        S   31.6833   
23   21.0              NaN  1979 10 07        C   61.3792   
24   48.0  B57 B59 B63 B66  1979 10 07        C  262.3750   
25   50.0              NaN  1979 10 07        S   14.5000   
26   22.0              B36  1979 10 07        C   61.9792   
27   22.5              NaN  1979 10 07        C    7.2250   
28   41.0              A21  1979 10 07        S   30.5000   
29    NaN              NaN  1979 10 07        C   21.6792   
..    ...              ...         ...      ...       ...   
388  21.0              NaN  1979 10 07        Q    7.7500   
389   6.0              NaN  1979 10 07        S   21.0750   
390  23.0              B24  1979 10 07        S   93.5000   
391  51.0              D28  1979 10 07        S   39.4000   
392  13.0              NaN  1979 10 07        S   20.2500   
393  47.0              NaN  1979 10 07        S   10.5000   
394  29.0              NaN  1979 10 07        S   22.0250   
395  18.0              C31  1979 10 07        S   60.0000   
396  24.0              NaN  1979 10 07        Q    7.2500   
397  48.0              B41  1979 10 07        C   79.2000   
398  22.0              NaN  1979 10 07        S    7.7750   
399  31.0              NaN  1979 10 07        Q    7.7333   
400  30.0               C7  1979 10 07        S  164.8667   
401  38.0              NaN  1979 10 07        S   21.0000   
402  22.0              NaN  1979 10 07        C   59.4000   
403  17.0              NaN  1979 10 07        S   47.1000   
404  43.0              D40  1979 10 07        C   27.7208   
405  20.0              D38  1979 10 07        C   13.8625   
406  23.0              NaN  1979 10 07        S   10.5000   
407  50.0              C80  1979 10 07        C  211.5000   
408   NaN              NaN  1979 10 07        Q    7.7208   
409   3.0              NaN  1979 10 07        S   13.7750   
410   NaN              NaN  1979 10 07        Q    7.7500   
411  37.0              C78  1979 10 07        Q   90.0000   
412  28.0              NaN  1979 10 07        S    7.7750   
413   NaN              NaN  1979 10 07        S    8.0500   
414  39.0             C105  1979 10 07        C  108.9000   
415  38.5              NaN  1979 10 07        S    7.2500   
416   NaN              NaN  1979 10 07        S    8.0500   
417   NaN              NaN  1979 10 07        C   22.3583   

                                                  Name  Parch  PassengerId  \
0                                     Kelly, Mr. James    0.0        892.0   
1                     Wilkes, Mrs. James (Ellen Needs)    0.0      

In [109]:
n=8
a=[]
for i in range(n):
    a.append([])
    a[i].append(1)
    for j in range(1,i):
        a[i].append(a[i-1][j-1]+a[i-1][j])
    if(n!=0):
        a[i].append(1)
for i in range(n):
    print("   "*(n-i),end=" ",sep=" ")
    for j in range(0,i+1):
        print('{0:6}'.format(a[i][j]),end=" ",sep=" ")
    print()

                              1 
                           1      1 
                        1      2      1 
                     1      3      3      1 
                  1      4      6      4      1 
               1      5     10     10      5      1 
            1      6     15     20     15      6      1 
         1      7     21     35     35     21      7      1 


In [114]:
P=lambda h:(lambda x:x+[[x+y for x,y in zip(x[-1]+[0],[0]+x[-1])]])(P(h-1))if h>1 else[[1]]
for i in P(6):
    print(i)

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
[1, 5, 10, 10, 5, 1]


In [115]:
df

Age            Cabin        Date Embarked      Fare  \
0    34.5              NaN  1979 10 07        Q    7.8292   
1    47.0              NaN  1979 10 07        S    7.0000   
2    62.0              NaN  1979 10 07        Q    9.6875   
3    27.0              NaN  1979 10 07        S    8.6625   
4    22.0              NaN  1979 10 07        S   12.2875   
5    14.0              NaN  1979 10 07        S    9.2250   
6    30.0              NaN  1979 10 07        Q    7.6292   
7    26.0              NaN  1979 10 07        S   29.0000   
8    18.0              NaN  1979 10 07        C    7.2292   
9    21.0              NaN  1979 10 07        S   24.1500   
10    NaN              NaN  1979 10 07        S    7.8958   
11   46.0              NaN  1979 10 07        S   26.0000   
12   23.0              B45  1979 10 07        S   82.2667   
13   63.0              NaN  1979 10 07        S   26.0000   
14   47.0              E31  1979 10 07        S   61.1750   
15   24.0              NaN  1979 10 07        C   27.7208   
16   35.0              NaN  1979 10 07        Q   12.3500   
17   21.0              NaN  1979 10 07        C    7.2250   
18   27.0              NaN  1979 10 07        S    7.9250   
19   45.0              NaN  1979 10 07        C    7.2250   
20   55.0              NaN  1979 10 07        C   59.4000   
21    9.0              NaN  1979 10 07        S    3.1708   
22    NaN              NaN  1979 10 07        S   31.6833   
23   21.0              NaN  1979 10 07        C   61.3792   
24   48.0  B57 B59 B63 B66  1979 10 07        C  262.3750   
25   50.0              NaN  1979 10 07        S   14.5000   
26   22.0              B36  1979 10 07        C   61.9792   
27   22.5              NaN  1979 10 07        C    7.2250   
28   41.0              A21  1979 10 07        S   30.5000   
29    NaN              NaN  1979 10 07        C   21.6792   
..    ...              ...         ...      ...       ...   
388  21.0              NaN  1979 10 07        Q    7.7500   
389   6.0              NaN  1979 10 07        S   21.0750   
390  23.0              B24  1979 10 07        S   93.5000   
391  51.0              D28  1979 10 07        S   39.4000   
392  13.0              NaN  1979 10 07        S   20.2500   
393  47.0              NaN  1979 10 07        S   10.5000   
394  29.0              NaN  1979 10 07        S   22.0250   
395  18.0              C31  1979 10 07        S   60.0000   
396  24.0              NaN  1979 10 07        Q    7.2500   
397  48.0              B41  1979 10 07        C   79.2000   
398  22.0              NaN  1979 10 07        S    7.7750   
399  31.0              NaN  1979 10 07        Q    7.7333   
400  30.0               C7  1979 10 07        S  164.8667   
401  38.0              NaN  1979 10 07        S   21.0000   
402  22.0              NaN  1979 10 07        C   59.4000   
403  17.0              NaN  1979 10 07        S   47.1000   
404  43.0              D40  1979 10 07        C   27.7208   
405  20.0              D38  1979 10 07        C   13.8625   
406  23.0              NaN  1979 10 07        S   10.5000   
407  50.0              C80  1979 10 07        C  211.5000   
408   NaN              NaN  1979 10 07        Q    7.7208   
409   3.0              NaN  1979 10 07        S   13.7750   
410   NaN              NaN  1979 10 07        Q    7.7500   
411  37.0              C78  1979 10 07        Q   90.0000   
412  28.0              NaN  1979 10 07        S    7.7750   
413   NaN              NaN  1979 10 07        S    8.0500   
414  39.0             C105  1979 10 07        C  108.9000   
415  38.5              NaN  1979 10 07        S    7.2500   
416   NaN              NaN  1979 10 07        S    8.0500   
417   NaN              NaN  1979 10 07        C   22.3583   

                                                  Name  Parch  PassengerId  \
0                                     Kelly, Mr. James    0.0        892.0   
1                     Wilkes, Mrs. James (Ellen Needs)    0.0      

In [116]:
df_check_date =df

In [118]:
df_check_date['Fare']=df_check_date['Fare'].apply(lambda x:round(x,2))
df_check_date

Age            Cabin        Date Embarked    Fare  \
0    34.5              NaN  1979 10 07        Q    7.83   
1    47.0              NaN  1979 10 07        S    7.00   
2    62.0              NaN  1979 10 07        Q    9.69   
3    27.0              NaN  1979 10 07        S    8.66   
4    22.0              NaN  1979 10 07        S   12.29   
5    14.0              NaN  1979 10 07        S    9.22   
6    30.0              NaN  1979 10 07        Q    7.63   
7    26.0              NaN  1979 10 07        S   29.00   
8    18.0              NaN  1979 10 07        C    7.23   
9    21.0              NaN  1979 10 07        S   24.15   
10    NaN              NaN  1979 10 07        S    7.90   
11   46.0              NaN  1979 10 07        S   26.00   
12   23.0              B45  1979 10 07        S   82.27   
13   63.0              NaN  1979 10 07        S   26.00   
14   47.0              E31  1979 10 07        S   61.17   
15   24.0              NaN  1979 10 07        C   27.72   
16   35.0              NaN  1979 10 07        Q   12.35   
17   21.0              NaN  1979 10 07        C    7.22   
18   27.0              NaN  1979 10 07        S    7.92   
19   45.0              NaN  1979 10 07        C    7.22   
20   55.0              NaN  1979 10 07        C   59.40   
21    9.0              NaN  1979 10 07        S    3.17   
22    NaN              NaN  1979 10 07        S   31.68   
23   21.0              NaN  1979 10 07        C   61.38   
24   48.0  B57 B59 B63 B66  1979 10 07        C  262.38   
25   50.0              NaN  1979 10 07        S   14.50   
26   22.0              B36  1979 10 07        C   61.98   
27   22.5              NaN  1979 10 07        C    7.22   
28   41.0              A21  1979 10 07        S   30.50   
29    NaN              NaN  1979 10 07        C   21.68   
..    ...              ...         ...      ...     ...   
388  21.0              NaN  1979 10 07        Q    7.75   
389   6.0              NaN  1979 10 07        S   21.07   
390  23.0              B24  1979 10 07        S   93.50   
391  51.0              D28  1979 10 07        S   39.40   
392  13.0              NaN  1979 10 07        S   20.25   
393  47.0              NaN  1979 10 07        S   10.50   
394  29.0              NaN  1979 10 07        S   22.02   
395  18.0              C31  1979 10 07        S   60.00   
396  24.0              NaN  1979 10 07        Q    7.25   
397  48.0              B41  1979 10 07        C   79.20   
398  22.0              NaN  1979 10 07        S    7.78   
399  31.0              NaN  1979 10 07        Q    7.73   
400  30.0               C7  1979 10 07        S  164.87   
401  38.0              NaN  1979 10 07        S   21.00   
402  22.0              NaN  1979 10 07        C   59.40   
403  17.0              NaN  1979 10 07        S   47.10   
404  43.0              D40  1979 10 07        C   27.72   
405  20.0              D38  1979 10 07        C   13.86   
406  23.0              NaN  1979 10 07        S   10.50   
407  50.0              C80  1979 10 07        C  211.50   
408   NaN              NaN  1979 10 07        Q    7.72   
409   3.0              NaN  1979 10 07        S   13.78   
410   NaN              NaN  1979 10 07        Q    7.75   
411  37.0              C78  1979 10 07        Q   90.00   
412  28.0              NaN  1979 10 07        S    7.78   
413   NaN              NaN  1979 10 07        S    8.05   
414  39.0             C105  1979 10 07        C  108.90   
415  38.5              NaN  1979 10 07        S    7.25   
416   NaN              NaN  1979 10 07        S    8.05   
417   NaN              NaN  1979 10 07        C   22.36   

                                                  Name  Parch  PassengerId  \
0                                     Kelly, Mr. James    0.0        892.0   
1                     Wilkes, Mrs. James (Ellen Needs)    0.0        893.0   
2                            Myles, Mr. Thomas Francis    0.0        894.0   
3                                  

In [120]:
import pandas as pd 
url='https://media-doselect.s3.amazonaws.com/generic/1YZQ77KLVyegqroyJgk5Z7d1/titaniMod2.csv'
df=pd.read_csv(url)
df = df.loc[:, df.isin([' ','NULL',0]).mean() < .5]
df = df.dropna(axis = 0, thresh=(df.shape[1])/2)
df.Date=df.Date.str.replace("-", "")
floats = ['float32', 'float64']
colsToRound=df.select_dtypes(include=floats).columns
colsToRound=df[colsToRound].round(decimals=2)
print(df.shape[0])
print(df.shape[1])
print(df.Date.head(10))
print(colsToRound.head())
df

418
13
0    19791007
1    19791007
2    19791007
3    19791007
4    19791007
5    19791007
6    19791007
7    19791007
8    19791007
9    19791007
Name: Date, dtype: object
    Age   Fare  Parch  PassengerId  Pclass  SibSp
0  34.5   7.83    0.0        892.0     3.0    0.0
1  47.0   7.00    0.0        893.0     3.0    1.0
2  62.0   9.69    0.0        894.0     2.0    0.0
3  27.0   8.66    0.0        895.0     3.0    0.0
4  22.0  12.29    1.0        896.0     3.0    1.0


Age            Cabin      Date Embarked      Fare  \
0    34.5              NaN  19791007        Q    7.8292   
1    47.0              NaN  19791007        S    7.0000   
2    62.0              NaN  19791007        Q    9.6875   
3    27.0              NaN  19791007        S    8.6625   
4    22.0              NaN  19791007        S   12.2875   
5    14.0              NaN  19791007        S    9.2250   
6    30.0              NaN  19791007        Q    7.6292   
7    26.0              NaN  19791007        S   29.0000   
8    18.0              NaN  19791007        C    7.2292   
9    21.0              NaN  19791007        S   24.1500   
10    NaN              NaN  19791007        S    7.8958   
11   46.0              NaN  19791007        S   26.0000   
12   23.0              B45  19791007        S   82.2667   
13   63.0              NaN  19791007        S   26.0000   
14   47.0              E31  19791007        S   61.1750   
15   24.0              NaN  19791007        C   27.7208   
16   35.0              NaN  19791007        Q   12.3500   
17   21.0              NaN  19791007        C    7.2250   
18   27.0              NaN  19791007        S    7.9250   
19   45.0              NaN  19791007        C    7.2250   
20   55.0              NaN  19791007        C   59.4000   
21    9.0              NaN  19791007        S    3.1708   
22    NaN              NaN  19791007        S   31.6833   
23   21.0              NaN  19791007        C   61.3792   
24   48.0  B57 B59 B63 B66  19791007        C  262.3750   
25   50.0              NaN  19791007        S   14.5000   
26   22.0              B36  19791007        C   61.9792   
27   22.5              NaN  19791007        C    7.2250   
28   41.0              A21  19791007        S   30.5000   
29    NaN              NaN  19791007        C   21.6792   
..    ...              ...       ...      ...       ...   
388  21.0              NaN  19791007        Q    7.7500   
389   6.0              NaN  19791007        S   21.0750   
390  23.0              B24  19791007        S   93.5000   
391  51.0              D28  19791007        S   39.4000   
392  13.0              NaN  19791007        S   20.2500   
393  47.0              NaN  19791007        S   10.5000   
394  29.0              NaN  19791007        S   22.0250   
395  18.0              C31  19791007        S   60.0000   
396  24.0              NaN  19791007        Q    7.2500   
397  48.0              B41  19791007        C   79.2000   
398  22.0              NaN  19791007        S    7.7750   
399  31.0              NaN  19791007        Q    7.7333   
400  30.0               C7  19791007        S  164.8667   
401  38.0              NaN  19791007        S   21.0000   
402  22.0              NaN  19791007        C   59.4000   
403  17.0              NaN  19791007        S   47.1000   
404  43.0              D40  19791007        C   27.7208   
405  20.0              D38  19791007        C   13.8625   
406  23.0              NaN  19791007        S   10.5000   
407  50.0              C80  19791007        C  211.5000   
408   NaN              NaN  19791007        Q    7.7208   
409   3.0              NaN  19791007        S   13.7750   
410   NaN              NaN  19791007        Q    7.7500   
411  37.0              C78  19791007        Q   90.0000   
412  28.0              NaN  19791007        S    7.7750   
413   NaN              NaN  19791007        S    8.0500   
414  39.0             C105  19791007        C  108.9000   
415  38.5              NaN  19791007        S    7.2500   
416   NaN              NaN  19791007        S    8.0500   
417   NaN              NaN  19791007        C   22.3583   

                                                  Name  Parch  PassengerId  \
0                                     Kelly, Mr. James    0.0        892.0   
1                     Wilkes, Mrs. James (Ellen Needs)    0.0        893.0   
2                            Myles, Mr. Thomas Francis    0.0        894.0   
3                                  

In [123]:
import pandas as pd 
pd.set_option('display.max_columns', 500)

df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/GVj4YrNpJwOvL7gBe2B53wJy/Admission_Predict.csv")
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000   
mean   200.500000  316.807500   107.410000           3.087500    3.400000   
std    115.614301   11.473646     6.069514           1.143728    1.006869   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    100.750000  308.000000   103.000000           2.000000    2.500000   
50%    200.500000  317.000000   107.000000           3.000000    3.500000   
75%    300.250000  325.000000   112.000000           4.000000    4.000000   
max    400.000000  340.000000   120.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     3.452500    8.598925    0.547500          0.724350  
std      0.898478    0.596317    0.498362          0.142609  
min      1.000000    6.800000    0.000000          0.340000  
25%      3.000000    8.170000    0.000000          0.640000  
50%      3.500000    8.610000    1.000000          0.730000  
75%      4.000000    9.062500    1.000000          0.830000  
max      5.000000    9.920000    1.000000          0.970000

In [142]:
import pandas as pd
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/GVj4YrNpJwOvL7gBe2B53wJy/Admission_Predict.csv")
print(df.describe())

       Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000   
mean   200.500000  316.807500   107.410000           3.087500    3.400000   
std    115.614301   11.473646     6.069514           1.143728    1.006869   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    100.750000  308.000000   103.000000           2.000000    2.500000   
50%    200.500000  317.000000   107.000000           3.000000    3.500000   
75%    300.250000  325.000000   112.000000           4.000000    4.000000   
max    400.000000  340.000000   120.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     3.452500    8.598925    0.547500          0.724350  
std      0.898478    0.596317    0.498362          0.142609  
min      1.000000    6.800000    0.000000          0.34000

In [143]:
import pandas as pd 
pd.set_option('display.max_columns', 500)
import sys,ast
input_str = ['Serial No.', 'GRE Score', 'TOEFL Score']

def normalize(df):
    result = df.copy()
    for input_str in df.columns:
        max_value = df[input_str].max()
        min_value = df[input_str].min()
        result[input_str] = (df[input_str] - min_value) / (max_value - min_value)
    return result

df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/GVj4YrNpJwOvL7gBe2B53wJy/Admission_Predict.csv")

df_normalize = normalize(df)
print(df_normalize.describe())


       Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count   400.00000  400.000000   400.000000         400.000000  400.000000   
mean      0.50000    0.536150     0.550357           0.521875    0.600000   
std       0.28976    0.229473     0.216768           0.285932    0.251717   
min       0.00000    0.000000     0.000000           0.000000    0.000000   
25%       0.25000    0.360000     0.392857           0.250000    0.375000   
50%       0.50000    0.540000     0.535714           0.500000    0.625000   
75%       0.75000    0.700000     0.714286           0.750000    0.750000   
max       1.00000    1.000000     1.000000           1.000000    1.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     0.613125    0.576579    0.547500          0.610079  
std      0.224619    0.191127    0.498362          0.226364  
min      0.000000    0.000000    0.000000          0.00000

In [280]:
import pandas as pd 
pd.set_option('display.max_columns', 500)
import sys,ast
input_str = ['Serial No.', 'GRE Score', 'TOEFL Score']
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/GVj4YrNpJwOvL7gBe2B53wJy/Admission_Predict.csv")
df[input_str] = df[input_str].apply(lambda x:(x-x.min()) / (x.max()-x.min()))
print(df.describe())
df.head(3)

       Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count   400.00000  400.000000   400.000000         400.000000  400.000000   
mean      0.50000    0.536150     0.550357           3.087500    3.400000   
std       0.28976    0.229473     0.216768           1.143728    1.006869   
min       0.00000    0.000000     0.000000           1.000000    1.000000   
25%       0.25000    0.360000     0.392857           2.000000    2.500000   
50%       0.50000    0.540000     0.535714           3.000000    3.500000   
75%       0.75000    0.700000     0.714286           4.000000    4.000000   
max       1.00000    1.000000     1.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     3.452500    8.598925    0.547500          0.724350  
std      0.898478    0.596317    0.498362          0.142609  
min      1.000000    6.800000    0.000000          0.34000

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0    0.000000       0.94     0.928571                  4  4.5   4.5  9.65   
1    0.002506       0.68     0.535714                  4  4.0   4.5  8.87   
2    0.005013       0.52     0.428571                  3  3.0   3.5  8.00   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72

In [151]:
import pandas as pd 
pd.set_option('display.max_columns', 500)

url='https://media-doselect.s3.amazonaws.com/generic/eJ5zayg0OnnX5PqMvAR8KQd9p/titanicmod.csv'

df=pd.read_csv(url)

df

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

In [152]:
print(df.shape)
print(df.info())

(418, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 14 columns):
PassengerId       418 non-null int64
Pclass            418 non-null int64
Name              418 non-null object
Sex               418 non-null object
Age               332 non-null float64
SibSp             418 non-null int64
Parch             418 non-null int64
Ticket            418 non-null object
Fare              417 non-null float64
Cabin             91 non-null object
Embarked          418 non-null object
Year              418 non-null int64
Ship              418 non-null object
Movie Director    418 non-null object
dtypes: float64(2), int64(5), object(7)
memory usage: 45.8+ KB
None


In [153]:
df.isnull()

PassengerId  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  \
0          False   False  False  False  False  False  False   False  False   
1          False   False  False  False  False  False  False   False  False   
2          False   False  False  False  False  False  False   False  False   
3          False   False  False  False  False  False  False   False  False   
4          False   False  False  False  False  False  False   False  False   
5          False   False  False  False  False  False  False   False  False   
6          False   False  False  False  False  False  False   False  False   
7          False   False  False  False  False  False  False   False  False   
8          False   False  False  False  False  False  False   False  False   
9          False   False  False  False  False  False  False   False  False   
10         False   False  False  False   True  False  False   False  False   
11         False   False  False  False  False  False  False   False  False   
12         False   False  False  False  False  False  False   False  False   
13         False   False  False  False  False  False  False   False  False   
14         False   False  False  False  False  False  False   False  False   
15         False   False  False  False  False  False  False   False  False   
16         False   False  False  False  False  False  False   False  False   
17         False   False  False  False  False  False  False   False  False   
18         False   False  False  False  False  False  False   False  False   
19         False   False  False  False  False  False  False   False  False   
20         False   False  False  False  False  False  False   False  False   
21         False   False  False  False  False  False  False   False  False   
22         False   False  False  False   True  False  False   False  False   
23         False   False  False  False  False  False  False   False  False   
24         False   False  False  False  False  False  False   False  False   
25         False   False  False  False  False  False  False   False  False   
26         False   False  False  False  False  False  False   False  False   
27         False   False  False  False  False  False  False   False  False   
28         False   False  False  False  False  False  False   False  False   
29         False   False  False  False   True  False  False   False  False   
..           ...     ...    ...    ...    ...    ...    ...     ...    ...   
388        False   False  False  False  False  False  False   False  False   
389        False   False  False  False  False  False  False   False  False   
390        False   False  False  False  False  False  False   False  False   
391        False   False  False  False  False  False  False   False  False   
392        False   False  False  False  False  False  False   False  False   
393        False   False  False  False  False  False  False   False  False   
394        False   False  False  False  False  False  False   False  False   
395        False   False  False  False  False  False  False   False  False   
396        False   False  False  False  False  False  False   False  False   
397        False   False  False  False  False  False  False   False  False   
398        False   False  False  False  False  False  False   False  False   
399        False   False  False  False  False  False  False   False  False   
400        False   False  False  False  False  False  False   False  False   
401        False   False  False  False  False  False  False   False  False   
402        False   False  False  False  False  False  False   False  False   
403        False   False  False  False  False  False  False   False  False   
404        False   False  False  False  False  False  False   False  False   
405        False   False  False  False  False  False  False   False  False   
406        False   False  False  False  False  False  False   False  False   
407        False   False  F

In [154]:
df.isnull().sum()

PassengerId         0
Pclass              0
Name                0
Sex                 0
Age                86
SibSp               0
Parch               0
Ticket              0
Fare                1
Cabin             327
Embarked            0
Year                0
Ship                0
Movie Director      0
dtype: int64

In [156]:
df_bkup =df

In [163]:
df_remove=df[df.isnull().sum(axis=1) < 2]
df_remove.isnull().sum()

PassengerId         0
Pclass              0
Name                0
Sex                 0
Age                 4
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin             244
Embarked            0
Year                0
Ship                0
Movie Director      0
dtype: int64

In [246]:
nunique = df_remove.apply(pd.Series.nunique)
cols_to_drop = nunique[nunique == 1].index
df_remove=df_remove.drop(cols_to_drop, axis=1)
df_remove

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
30           922       2                       Louch, Mr. Charles Alexander   
31           923       2                      Jefferys, Mr. Clifford Thomas   
32           924       3           Dean, Mrs. Bertram (Eva Georgetta Light)   
..           ...     ...                                                ...   
381         1273       3                                  Foley, Mr. Joseph   
383         1275       3                McNamee, Mrs. Neal (Eileen O'Leary)   
385         1277       2                                 Herman, Miss. Kate   
386         1278       3                     Aronsson, Mr. Ernst Axel Algot   
387         1279       2                                    Ashby, Mr. John   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                               

In [270]:
#(df_remove.Year<1900).sum()
count=0
checkcount=0
for index, row in df_remove.iterrows():
    if(row.Year<1900):
        count = count+1
    if(row.Year>2018):
        checkcount = checkcount+1
   
        
print(count)
print(checkcount)  
print(checkcount+count)

52
19
71


In [179]:
df_remove_backup=df_remove

In [181]:
df_remove_duplicates=df_remove.drop_duplicates()
df_remove_duplicates.shape

(335, 12)

In [245]:
#list_year = [2018,]


df_remove_year =df_remove_duplicates[(df_remove_duplicates.Year <= 2018)&(df_remove_duplicates.Year >=1900) ]

df_remove_year

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
28           920       1                            Brady, Mr. John Bertram   
31           923       2                      Jefferys, Mr. Clifford Thomas   
32           924       3           Dean, Mrs. Bertram (Eva Georgetta Light)   
34           926       1                           Mock, Mr. Philipp Edmund   
35           927       3   Katavelas, Mr. Vassilios (Catavelas Vassilios")"   
37           929       3                                 Cacic, Miss. Manda   
38           930       3                                    Sap, Mr. Julius   
40           932       3                                   Karun, Mr. Franz   
41           933       1                        Franklin, Mr. Thomas Parham   
42           934       3                              Goldsmith, Mr. Nathan   
43           935       2              Corbett, Mrs. Walter H (Irene Colvin)   
..           ...     ...                                                ...   
373         1265       2                             Harbeck, Mr. William H   
376         1268       3                                  Kink, Miss. Maria   
377         1269       2                       Cotterill, Mr. Henry Harry""   
379         1271       3                        Asplund, Master. Carl Edgar   
381         1273       3                                  Foley, Mr. Joseph   
383         1275       3                McNamee, Mrs. Neal (Eileen O'Leary)   
385         1277       2                                 Herman, Miss. Kate   
386         1278       3                     Aronsson, Mr. Ernst Axel Algot   
387         1279       2                                    Ashby, Mr. John   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conl

In [216]:
df_remove_dupe = df_remove_year.drop_duplicates()
df_remove_dupe

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
28           920       1                            Brady, Mr. John Bertram   
31           923       2                      Jefferys, Mr. Clifford Thomas   
32           924       3           Dean, Mrs. Bertram (Eva Georgetta Light)   
34           926       1                           Mock, Mr. Philipp Edmund   
35           927       3   Katavelas, Mr. Vassilios (Catavelas Vassilios")"   
37           929       3                                 Cacic, Miss. Manda   
38           930       3                                    Sap, Mr. Julius   
40           932       3                                   Karun, Mr. Franz   
41           933       1                        Franklin, Mr. Thomas Parham   
42           934       3                              Goldsmith, Mr. Nathan   
43           935       2              Corbett, Mrs. Walter H (Irene Colvin)   
..           ...     ...                                                ...   
373         1265       2                             Harbeck, Mr. William H   
376         1268       3                                  Kink, Miss. Maria   
377         1269       2                       Cotterill, Mr. Henry Harry""   
379         1271       3                        Asplund, Master. Carl Edgar   
381         1273       3                                  Foley, Mr. Joseph   
383         1275       3                McNamee, Mrs. Neal (Eileen O'Leary)   
385         1277       2                                 Herman, Miss. Kate   
386         1278       3                     Aronsson, Mr. Ernst Axel Algot   
387         1279       2                                    Ashby, Mr. John   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conl

In [219]:
df_remove_dupe
round(100*(df_remove_dupe.isnull().sum()/len(df_remove_dupe.index)), 2)

PassengerId     0.00
Pclass          0.00
Name            0.00
Sex             0.00
Age             1.53
SibSp           0.00
Parch           0.00
Ticket          0.00
Fare            0.00
Cabin          73.66
Embarked        0.00
Year            0.00
dtype: float64

In [220]:
df_remove_dupe = df_remove_dupe[~np.isnan(df_remove_dupe['Age'])]

In [221]:
round(100*(df_remove_dupe.isnull().sum()/len(df_remove_dupe.index)), 2)

PassengerId     0.00
Pclass          0.00
Name            0.00
Sex             0.00
Age             0.00
SibSp           0.00
Parch           0.00
Ticket          0.00
Fare            0.00
Cabin          74.81
Embarked        0.00
Year            0.00
dtype: float64

In [223]:
type(df_remove_dupe['Name'])

pandas.core.series.Series

In [224]:
df_remove_dupe

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
28           920       1                            Brady, Mr. John Bertram   
31           923       2                      Jefferys, Mr. Clifford Thomas   
32           924       3           Dean, Mrs. Bertram (Eva Georgetta Light)   
34           926       1                           Mock, Mr. Philipp Edmund   
35           927       3   Katavelas, Mr. Vassilios (Catavelas Vassilios")"   
37           929       3                                 Cacic, Miss. Manda   
38           930       3                                    Sap, Mr. Julius   
40           932       3                                   Karun, Mr. Franz   
42           934       3                              Goldsmith, Mr. Nathan   
43           935       2              Corbett, Mrs. Walter H (Irene Colvin)   
44           936       1   Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)   
..           ...     ...                                                ...   
373         1265       2                             Harbeck, Mr. William H   
376         1268       3                                  Kink, Miss. Maria   
377         1269       2                       Cotterill, Mr. Henry Harry""   
379         1271       3                        Asplund, Master. Carl Edgar   
381         1273       3                                  Foley, Mr. Joseph   
383         1275       3                McNamee, Mrs. Neal (Eileen O'Leary)   
385         1277       2                                 Herman, Miss. Kate   
386         1278       3                     Aronsson, Mr. Ernst Axel Algot   
387         1279       2                                    Ashby, Mr. John   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conl

In [276]:
df_remove_dupe_cabin = df_remove_dupe.dropna(axis = 0)


In [277]:
df_remove_dupe_cabin

PassengerId  Pclass                                               Name  \
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
26           918       1                       Ostby, Miss. Helene Ragnhild   
28           920       1                            Brady, Mr. John Bertram   
34           926       1                           Mock, Mr. Philipp Edmund   
44           936       1   Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)   
46           938       1                           Chevre, Mr. Paul Romaine   
50           942       1                           Smith, Mr. Lucien Philip   
57           949       3                      Abelseth, Mr. Olaus Jorgensen   
59           951       1                        Chaudanson, Miss. Victorine   
64           956       1                        Ryerson, Master. John Borie   
68           960       1                    Tucker, Mr. Gilbert Milligan Jr   
69           961       1                Fortune, Mrs. Mark (Mary McDougald)   
73           965       1                    Ovies y Rodriguez, Mr. Servando   
74           966       1                               Geiger, Miss. Amalie   
92           984       1               Davidson, Mrs. Thornton (Orian Hays)   
96           988       1  Cavendish, Mrs. Tyrell William (Julia Florence...   
109         1001       2                                  Swane, Mr. George   
112         1004       1                           Evans, Miss. Edith Corse   
118         1010       1                               Beattie, Mr. Thomson   
122         1014       1                    Schabert, Mrs. Paul (Emma Mock)   
131         1023       1                          Gracie, Col. Archibald IV   
142         1034       1                         Ryerson, Mr. Arthur Larned   
150         1042       1              Earnshaw, Mrs. Boulton (Olive Potter)   
156         1048       1                                  Bird, Miss. Ellen   
158         1050       1                           Borebank, Mr. John James   
166         1058       1                                 Brandeis, Mr. Emil   
177         1069       1                    Stengel, Mr. Charles Emil Henry   
181         1073       1                   Compton, Mr. Alexander Taylor Jr   
182         1074       1  Marvin, Mrs. Daniel Warner (Mary Graham Carmic...   
..           ...     ...                                                ...   
236         1128       1                           Warren, Mr. Frank Manley   
239         1131       1        Douglas, Mrs. Walter Donald (Mahala Dutton)   
242         1134       1                       Spedden, Mr. Frederic Oakley   
245         1137       1                            Kenyon, Mr. Frederick R   
252         1144       1                           Clark, Mr. Walter Miller   
272         1164       1      Clark, Mrs. Walter Miller (Virginia McDowell)   
287         1179       1                         Snyder, Mr. John Pillsbury   
293         1185       1                              Dodge, Dr. Washington   
305         1197       1  Crosby, Mrs. Edward Gifford (Catherine Elizabe...   
306         1198       1               Allison, Mr. Hudson Joshua Creighton   
308         1200       1                         Hays, Mr. Charles Melville   
321         1213       3                              Krekorian, Mr. Neshan   
322         1214       2                                 Nesson, Mr. Israel   
326         1218       2                       Becker, Miss. Ruth Elizabeth   
331         1223       1                       Dulles, Mr. William Crothers   
335         1227       1                           Maguire, Mr. John Edward   
343         1235       1  Cardeza, Mrs. James Warburton Martinez (Charlo...   
350         1242       1       Greenfield, Mrs. Leo David (Blanche Strouse)   
355         1247       1                           Juli

In [228]:
round(100*(df_remove_dupe_cabin.isnull().sum()/len(df_remove_dupe_cabin.index)), 2)

PassengerId       0.0
Pclass            0.0
Name              0.0
Sex               0.0
Age               0.0
SibSp             0.0
Parch             0.0
Ticket            0.0
Fare              0.0
Cabin             0.0
Embarked          0.0
Year              0.0
Ship              0.0
Movie Director    0.0
dtype: float64

In [230]:



df_remove_dupe_cabin.select_dtypes(include=[np.number])


list_values =df_remove_dupe_cabin.select_dtypes(include=[np.number]).columns.tolist()
list_values

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Year']

In [231]:
df_remove_dupe_cabin.info(0)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87 entries, 12 to 414
Data columns (total 14 columns):
PassengerId       87 non-null int64
Pclass            87 non-null int64
Name              87 non-null object
Sex               87 non-null object
Age               87 non-null float64
SibSp             87 non-null int64
Parch             87 non-null int64
Ticket            87 non-null object
Fare              87 non-null float64
Cabin             87 non-null object
Embarked          87 non-null object
Year              87 non-null int64
Ship              87 non-null object
Movie Director    87 non-null object
dtypes: float64(2), int64(5), object(7)
memory usage: 10.2+ KB


In [278]:
print(df_remove_dupe_cabin.shape[0])

65


In [279]:
print(df_remove_dupe_cabin.shape[1])

12


Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Year', 'Ship',
       'Movie Director'],
      dtype='object')

PassengerId  Pclass                                               Name  \
12          904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
14          906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
24          916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   

       Sex   Age  SibSp  Parch       Ticket      Fare            Cabin  \
12  female  23.0      1      0        21228   82.2667              B45   
14  female  47.0      1      0  W.E.P. 5734   61.1750              E31   
24  female  48.0      1      3     PC 17608  262.3750  B57 B59 B63 B66   

   Embarked  Year     Ship Movie Director  
12        S  1915  Titanic  James Cameron  
14        S  1899  Titanic  James Cameron  
24        C  1988  Titanic  James Cameron

In [176]:
import numpy as np

a=np.arange(120).reshape(2,3,4,5)
print(a)
print(a.shape)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]
(2, 3, 4, 5)


In [178]:
np.sum(a,axis=0).shape

(3, 4, 5)