In [13]:
# Generating a random 1000 * 300 array

import numpy as nump
rand_array = nump.random.random((1000,300))
# print(rand_array)
# Printing the first row.
print(rand_array[0,])
print("Array Shape",rand_array.shape)
print("dtype", rand_array.dtype)
print("ndim", rand_array.ndim)
print("itemsize", rand_array.itemsize)

[0.65258074 0.91835479 0.37901756 0.19275079 0.71297992 0.02782931
 0.06578145 0.8626776  0.41001527 0.24146648 0.83739303 0.32363042
 0.68990867 0.05028445 0.41645169 0.32251154 0.3555709  0.61127198
 0.83003887 0.62485346 0.49868393 0.50372758 0.64633367 0.69208699
 0.48648449 0.79474687 0.70986111 0.90219743 0.52778121 0.75045439
 0.66597132 0.46852165 0.55217627 0.15371022 0.45305379 0.85075553
 0.94051812 0.19470387 0.96715062 0.64410712 0.88331572 0.39434985
 0.51378002 0.10088166 0.73921807 0.18068159 0.57883377 0.3172038
 0.899754   0.81883165 0.73458025 0.79551012 0.17468991 0.45581081
 0.45842725 0.04890806 0.65098537 0.56461795 0.8840796  0.31256753
 0.06905831 0.35522097 0.84599707 0.16043077 0.52942103 0.69173158
 0.27796126 0.28173315 0.35909793 0.77734282 0.33264354 0.79779713
 0.06073561 0.50355438 0.19807299 0.61329388 0.31417519 0.83102435
 0.57735222 0.01232111 0.82164294 0.55872685 0.2316349  0.03374315
 0.31110904 0.38239554 0.78175775 0.10796505 0.12196263 0.58148

In [18]:
# Higher Dimensional Arrays with 3 and above.
array_3d = nump.arange(24).reshape(2,3,4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [33]:
list_1 = [10,11,12,13] 
list_2 = [15,12,13,14]

x = nump.array([list_1, list_2])
print(x)

[[10 11 12 13]
 [15 12 13 14]]


In [34]:
# Slicing in Arrays

array_2d = nump.arange(10)
print(array_2d)


[0 1 2 3 4 5 6 7 8 9]


In [45]:
print(array_2d[2])
# third element onwards
print(array_2d[2:])
#fourth element onwards
print(array_2d[3:])

#Slice of first three elements

print(array_2d[:3])
#Slice of third to seventh element
print(array_2d[2:7])
#Subset starting 0 at increment of 2
print(array_2d[0::2])
# print all the elements
print(array_2d[::])
# Increment array element by 2
print(array_2d[::2])
#increment array element by 3
print(array_2d[0::3])

2
[2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]


In [50]:
# Create a 2D array.

array_2d_1 = nump.array([[2,5,7,5],[4,6,8,10],[10,12,15,19]])
print(array_2d_1)

# accessing third row second column

print(array_2d_1[2][1])
# Correct way of accessing the array.
print(array_2d_1[2,1])

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]
12
12


In [56]:
#print(array_2d_1)
#Second row and all columns
print(array_2d_1[1,:])

#Slicing all rows and thrid column
print(array_2d_1[:,2])

#Slicing all rows and first three columns
print(array_2d_1[:,:3])

#Printing all rows and all columns
print(array_2d_1[::])

[ 4  6  8 10]
[ 7  8 15]
[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]
[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [57]:
#printing the 2d array

for row in array_2d_1:
    print(row)

[2 5 7 5]
[ 4  6  8 10]
[10 12 15 19]


In [58]:
#Creating a 3D array

array_3d  = nump.arange(24).reshape(2,3,4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [59]:
for row in array_3d:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [72]:
array_2d = nump.array([[5,6,7],[7,6,5],[0,8,7]])
#print(array_2d)
print(array_2d[:,1])

[6 6 8]


In [79]:
array_2d_1= nump.array([[11, 12, 13, 14],
 [21, 22, 23, 24],
 [31, 32, 33, 34]])
#Col First
print(array_2d_1[:,0])
#Row First
print(array_2d_1[0,:])
#Col Last
print(array_2d_1[:,3])
#Row Last
print(array_2d_1[2:,])

[11 21 31]
[11 12 13 14]
[14 24 34]
[[31 32 33 34]]
