<h2>Manipulate arrays</h2>
    <ul>
        <li>Reshape arrays</li>
        <li>Stack arrays</li>
    </ul>
    
    
<h2>Perform operations on arrays</h2>
<ul>
    
   <li> Perform basic mathematical operations </li>
   <li> Apply built-in functions</li>
   <li> Apply your own functions</li>
   <li> Apply basic linear algebra operations</li>
    
</ul>
   

In [3]:
#Basic Operations
#Manipulating Arrays
#We can manipulate arrays changing the shape, combining and splitting the arrays.
# Reshaping can be done by Stacking and Splitting the arrays - reshaping can be done by reshape() function.
# Stacking and Splitting the Arrays
#Stacking: np.hstack() and np.vstack()
#Stacking is done using the np.hstack() and np.vstack() methods. 
#For horizontal stacking, the number of rows should be the same, while for vertical stacking, 
#the number of columns should be the same.


In [8]:
import numpy as nump

some_array = nump.arange(0,12).reshape(3,4)
print(some_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
# Can reshape it to further
some_array=some_array.reshape(2,6)
print(some_array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [10]:
# With reshape(4, -1) we specify one dimension and let numpy figure out the other one

some_array_reshape=some_array.reshape(4, -1)
print(some_array_reshape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
# Returns the array with a transpose we do with some_array_reshape.T

print(some_array_reshape.T)
print(some_array_reshape.T.ndim)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
2


In [18]:
# Creating two arrays where columns are same

array_1 = nump.arange(12).reshape(3,4)
array_2 = nump.arange(20).reshape(5,4)
print(array_1)
print("\n")
print(array_2)

print("\n\n")
#Vertical stack, need to pass arrays as list. The vertical stack is used when the columns are same.
array_vstack=nump.vstack([array_2,array_1])
print(array_vstack)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
# Horizontal stack where the columns are some

array_h1 = nump.arange(12).reshape(4, 3)
array_h2 = nump.arange(20).reshape(4, 5)

print(array_h1)
print("\n")
print(array_h2)

array_h3 = nump.hstack([array_h1, array_h2])

print("\n")

print(array_h3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 0  1  2  0  1  2  3  4]
 [ 3  4  5  5  6  7  8  9]
 [ 6  7  8 10 11 12 13 14]
 [ 9 10 11 15 16 17 18 19]]


In [31]:
complete_list = [[[1, 2], [5, 6]], [[3, 4], [7, 8]], [[9, 10, 11, 12]]]
list_1=complete_list[0]
list_2=complete_list[1]
list_3=complete_list[2]

print(list_1)
print(list_2)
print(list_3)

array_hstack = nump.hstack([list_1, list_2])
print(array_hstack)

array_vstack = nump.array(list_3)
print(array_vstack)
print("\n")
array_vstack = nump.vstack([array_hstack,array_vstack])
print(array_vstack)


[[1, 2], [5, 6]]
[[3, 4], [7, 8]]
[[9, 10, 11, 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<h2> Operations On Arrays </h2>
<b> numpy provides the basic mathematical operations as below </b>
<ol>
    <li> Exp </li>
    <li> Sin </li>
    <li> Cos </li>
    <li> Sqrt</li>
 </ol>
 <b> Functions above are applied to each element in the function </b>
 <p> You can apply your own funcions on the array. For eg: to apply function X/(1+X) to each of the elements in the array
    one way to do it is loop through the array. We need to write it through an vectorized way.
    The simplest way to do is to vecotrize the function and then apply it to all the elements in the array.
    The numpy provides the fucntion num.vectorize() method to vectorize the functions.
  </p>

In [42]:
# Operations on arrays.
a = nump.arange(1,20)
print(a)
print("\n")
print(nump.sin(a))
print("\n")
print(nump.cos(a))
print("\n")
print(nump.exp(a))
print("\n")
print(nump.sqrt(a))
print("\n")
print(nump.log(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721]


[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334  0.66031671
  0.98870462]


[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08]


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.       

In [45]:
alist = [x/(x+1) for x in a]
print(alist)

[0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95]


In [61]:
import time

time1x = time.time()
alist = [x/(x+1) for x in a]
print(alist)
time2x = time.time()
print("\n")
print(time2x - time1x)

#Vectorize the function with lambda expression.
f = nump.vectorize(lambda x:x/(x+1))
f(a)




[0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95]


0.0009982585906982422


array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [70]:
input_list = [[1,2,3,4],[4,7,5,6],[9,0,7,8],[6,7,8,5]]
list_1 = input_list[0:2]
list_2 = input_list[2:4]
print(list_1)
print(list_2)
array_list_1 = nump.array(list_1)
array_list_2 = nump.array(list_2)
print("\n")
array_list_3 = nump.hstack([array_list_1, array_list_2])
print(array_list_3)
print("\n")

function = nump.vectorize(lambda x:x/5)
print(function(array_list_3))

[[1, 2, 3, 4], [4, 7, 5, 6]]
[[9, 0, 7, 8], [6, 7, 8, 5]]


[[1 2 3 4 9 0 7 8]
 [4 7 5 6 6 7 8 5]]


[[0.2 0.4 0.6 0.8 1.8 0.  1.4 1.6]
 [0.8 1.4 1.  1.2 1.2 1.4 1.6 1. ]]


<h2> Basic Linear Operations </h2>
NumPy provides the <b>np.linalg</b> package to apply common linear algebra operations, such as:
<ul> 
    <li>np.linalg.inv: Inverse of a matrix</li>
    <li>np.linalg.det: Determinant of a matrix</li>
    <li>np.linalg.eig: Eigenvalues and eigenvectors of a matrix</li>
</ul>
<b>Also, you can multiply matrices using np.dot(a, b) </b>


In [75]:
# Creating arrays

array_1 = nump.arange(1,10).reshape(3,3)
array_2 = nump.arange(1,13).reshape(3,4)
print(array_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
# inverse of a matrix
nump.linalg.inv(array_1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [78]:
# Determinant of a matrix
nump.linalg.det(array_1)

-9.51619735392994e-16

In [79]:
# multiplication of two matrices

nump.dot(array_1, array_2)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])