In [3]:
import pandas as pd
import numpy as np

global_superStore_orders = pd.read_excel("D:/upgrad/global_superstore/GlobalSuperstore.xlsx","Orders")


Row ID         Order ID Order Date  Ship Date       Ship Mode  \
0       32298   CA-2012-124891 2012-07-31 2012-07-31        Same Day   
1       26341    IN-2013-77878 2013-02-05 2013-02-07    Second Class   
2       25330    IN-2013-71249 2013-10-17 2013-10-18     First Class   
3       13524  ES-2013-1579342 2013-01-28 2013-01-30     First Class   
4       47221     SG-2013-4320 2013-11-05 2013-11-06        Same Day   
5       22732    IN-2013-42360 2013-06-28 2013-07-01    Second Class   
6       30570    IN-2011-81826 2011-11-07 2011-11-09     First Class   
7       31192    IN-2012-86369 2012-04-14 2012-04-18  Standard Class   
8       40155   CA-2014-135909 2014-10-14 2014-10-21  Standard Class   
9       40936   CA-2012-116638 2012-01-28 2012-01-31    Second Class   
10      34577   CA-2011-102988 2011-04-05 2011-04-09    Second Class   
11      28879    ID-2012-28402 2012-04-19 2012-04-22     First Class   
12      45794     SA-2011-1830 2011-12-27 2011-12-29    Second Class   
13       4132   MX-2012-130015 2012-11-13 2012-11-13        Same Day   
14      27704    IN-2013-73951 2013-06-06 2013-06-08    Second Class   
15      13779  ES-2014-5099955 2014-07-31 2014-08-03    Second Class   
16      36178   CA-2014-143567 2014-11-03 2014-11-06    Second Class   
17      12069  ES-2014-1651774 2014-09-08 2014-09-14  Standard Class   
18      22096    IN-2014-11763 2014-01-31 2014-02-01     First Class   
19      49463     TZ-2014-8190 2014-12-05 2014-12-07    Second Class   
20      46630     PL-2012-7820 2012-08-08 2012-08-10     First Class   
21      31784   CA-2011-154627 2011-10-29 2011-10-31     First Class   
22      21586    IN-2011-44803 2011-05-02 2011-05-03     First Class   
23      13528  ES-2013-2860574 2013-02-27 2013-03-01    Second Class   
24       1570   US-2014-133193 2014-07-31 2014-08-01     First Class   
25       3484   MX-2014-165309 2014-09-05 2014-09-08     First Class   
26      30191    IN-2011-10286 2011-12-17 2011-12-20     First Class   
27      11645  ES-2011-4699764 2011-03-14 2011-03-17    Second Class   
28      37311   CA-2013-159016 2013-03-11 2013-03-12     First Class   
29      22999    IN-2012-44810 2012-02-25 2012-02-25        Same Day   
...       ...              ...        ...        ...             ...   
51260   40079   CA-2013-116911 2013-09-16 2013-09-21  Standard Class   
51261   43851     RS-2014-3790 2014-12-17 2014-12-20    Second Class   
51262   51055     CA-2014-6810 2014-12-23 2014-12-23        Same Day   
51263    6367   MX-2011-131688 2011-12-22 2011-12-26  Standard Class   
51264   13800  ES-2014-5679681 2014-08-05 2014-08-11  Standard Class   
51265   15975  ES-2011-4021337 2011-05-10 2011-05-14  Standard Class   
51266   22589    IN-2014-32000 2014-11-25 2014-11-30  Standard Class   
51267   27081    ID-2012-36725 2012-08-10 2012-08-11     First Class   
51268   34657   US-2012-142020 2012-06-04 2012-06-08    Second Class   
51269   36834   US-2013-167472 2013-06-07 2013-06-08     First Class   
51270   38414   CA-2011-143168 2011-10-18 2011-10-23    Second Class   
51271   47274       SA-2014-10 2014-04-09 2014-04-13  Standard Class   
51272    5465   MX-2014-101980 2014-04-17 2014-04-20    Second Class   
51273    5596   MX-2013-134600 2013-09-30 2013-10-02    Second Class   
51274    9309   MX-2014-162803 2014-09-11 2014-09-12     First Class   
51275   10410  ES-2011-1406120 2011-12-03 2011-12-03        Same Day   
51276   31558   US-2014-155299 2014-06-09 2014-06-13  Standard Class   
51277   37361   CA-2012-111780 2012-12-25 2012-12-30    Second Class   
51278   43818     NI-2011-4700 2011-09-08 2011-09-10    Second Class   
51279   46231     ZI-2011-4350 2011-03-21 2011-03-26  Standard Class   
51280   46582     TU-2014-6730 2014-11-29 2014-11-30     First Class   
51281    6039   MX-2014-169530 2014-06-09 2014-06-11     First Class   
51282    9922   MX-2012-100258 2012-12-28 2012-12-31     First Class   
51283   24105    IN-2014-72327 2014-05-30 2014-

In [10]:
global_superstores_indexed=global_superStore_orders.set_index("Row ID")
global_superstores_indexed.columns
global_superstores_indexed.shape
global_superstores_indexed.describe()
global_superstores_indexed['Profit'].max()

weather_dateframe_snow=global_superstores_indexed[['date','snow fall']][weather_dateframe['snow fall']==weather_dateframe['snow fall'].max()]

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.numeric.Int64Index'> with these indexers [Profit] of <class 'str'>

In [16]:
import numpy as npy

arry1=npy.arange(132).reshape(11,12)


In [20]:
arry1[:,:3]

array([[  0,   1,   2],
       [ 12,  13,  14],
       [ 24,  25,  26],
       [ 36,  37,  38],
       [ 48,  49,  50],
       [ 60,  61,  62],
       [ 72,  73,  74],
       [ 84,  85,  86],
       [ 96,  97,  98],
       [108, 109, 110],
       [120, 121, 122]])

In [29]:
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])
a

array([[4, 3, 1],
       [5, 7, 0],
       [9, 9, 3],
       [8, 2, 4]])

In [28]:
a[[0, 2]] = a[[2, 0]]
a

array([[9, 9, 3],
       [5, 7, 0],
       [4, 3, 1],
       [8, 2, 4]])

In [75]:
a[1:-1,1:-1] =0

In [76]:
n=4
x = np.ones([n,n], dtype=int)
x[1:-1,1:-1] = 0
print(x)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]
